#!/bin/sh
#
# Quality Assurance tests

# Install coding standards
echo "Installing coding standards..."
./vendor/bin/phpcs --config-set installed_paths $(pwd)/vendor/wp-coding-standards/wpcs/

# Check out code
echo "Runing coding standards"
./vendor/bin/phpcs --standard="WordPress" html/app/themes/gcit/ --extensions="php" --ignore=""
